kind: Template
apiVersion: v1
objects:
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    spec:
      replicas: 3
      selector:
        app: ${NAME}-${SUFFIX}
        version: ${IMAGE_TAG}
        pr: ${PULL_REQUEST_NUMBER}
        group: ${NAME}
        deploymentconfig: ${NAME}-${SUFFIX}
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          annotations:
            openshift.io/generated-by: OpenShiftWebConsole
          creationTimestamp: null
          labels:
            app: ${NAME}-${SUFFIX}
            version: ${IMAGE_TAG}
            pr: ${PULL_REQUEST_NUMBER}
            group: ${NAME}
            deploymentconfig: ${NAME}-${SUFFIX}
        spec:
          volumes:
            - configMap:
                defaultMode: 420
                name: caddyfile-${SUFFIX}
              name: caddyfile-volume
          containers:
            - image: >-
                ${IMAGE_NAMESPACE}/${IMAGE_STREAM}:${IMAGE_TAG}
              imagePullPolicy: Always
              name: ${NAME}-${SUFFIX}
              resources: 
                requests:
                  memory: ${MEMORY_REQUEST}
                  cpu: ${CPU_REQUEST}
                limits:
                  memory: ${MEMORY_LIMIT}
                  cpu: ${CPU_LIMIT}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /opt/app-root/etc/Caddyfile
                  name: caddyfile-volume
                  readOnly: true
                  subPath: Caddyfile
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}-${SUFFIX}
            from:
              kind: ImageStreamTag
              name: '${IMAGE_STREAM}:${IMAGE_TAG}'
              namespace: ${IMAGE_NAMESPACE}
          type: ImageChange
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
      generation: 6
      labels:
        app: ${NAME}-${SUFFIX}
        version: ${IMAGE_TAG}
        pr: ${PULL_REQUEST_NUMBER}
        group: ${NAME}
      name: ${NAME}-${SUFFIX}
  - apiVersion: v1
    data:
      Caddyfile: |
        :4000

        # for app
        root * /opt/app-root/src

        file_server 
        encode gzip

        try_files {path} {path}/ /index.html
        log stdout
        log stderr

        header / {
          # prevent any static html from being cached
          Cache-Control "public, max-age=0, must-revalidate"
        }
    kind: ConfigMap
    metadata:
      labels:
        build: digital-gov-frontend
        app: ${NAME}-${SUFFIX}
        version: ${IMAGE_TAG}
        pr: ${PULL_REQUEST_NUMBER}
        group: ${NAME}
      name: caddyfile-${SUFFIX}
  - apiVersion: v1
    kind: Service
    spec:
      ports:
        - name: 4000-4000
          port: 4000
          protocol: TCP
          targetPort: 4000
      selector:
        app: ${NAME}-${SUFFIX}
        version: ${IMAGE_TAG}
        pr: ${PULL_REQUEST_NUMBER}
        group: ${NAME}
      sessionAffinity: None
      type: ClusterIP
    metadata:
      labels:
        app: ${NAME}-${SUFFIX}
        version: ${IMAGE_TAG}
        pr: ${PULL_REQUEST_NUMBER}
        group: ${NAME}
      name: ${NAME}-${SUFFIX}
  - apiVersion: route.openshift.io/v1
    kind: Route
    spec:
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
      port:
        targetPort: 4000-4000
      to:
        kind: Service
        name: ${NAME}-${SUFFIX}
        weight: 100
      wildcardPolicy: None
    metadata:
      annotations:
        openshift.io/host.generated: 'true'
      labels:
        app: ${NAME}-${SUFFIX}
        version: ${IMAGE_TAG}
        pr: ${PULL_REQUEST_NUMBER}
        group: ${NAME}
      name: ${NAME}-${SUFFIX}
  
parameters:
- name: IMAGE_NAMESPACE
  required: true
  description: the namespace to pull the image from 
  displayName: Image Namespace
- name: IMAGE_STREAM
  required: true
  displayName: Image Stream 
  description: the name of the image stream the image is pulled from 
- name: IMAGE_TAG
  required: true
  displayName: Image Tag 
  description: the tag for the image to deploy
- name: NAME
  required: true
  displayName: name
  description: the name for the dc and container
  value: digital-gov-frontend
- name: CPU_REQUEST
  value: 50m 
- name: MEMORY_REQUEST
  value: 50Mi 
- name: CPU_LIMIT
  value: 70m 
- name: MEMORY_LIMIT
  value: 75Mi 
- name: SUFFIX
  required: true
  description: a suffix used in conjunction with NAME to further isolate different instances of these components
  displayName: suffix
- name: PULL_REQUEST_NUMBER
  default: 0
  required: false 
  description: The pull request number associated with this object
  displayName: Pull Request Number