kind: Template
apiVersion: v1
objects:
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    spec:
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        app: digital-strapi
        deploymentconfig: digital-strapi
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          annotations:
            openshift.io/generated-by: OpenShiftNewApp
          creationTimestamp: null
          labels:
            app: digital-strapi
            deploymentconfig: digital-strapi
        spec:
          containers:
            - image: >-
                docker-registry.default.svc:5000/xdwiwd-tools/digital-strapi@sha256:cf3813e27bf4b26ee0db4fec39253ba88aa8cee1e6bf3ada20ce7aefa42b1e01
              imagePullPolicy: IfNotPresent
              name: digital-strapi
              env:
                # One of these two configs should work
                - name: DATABASE_HOST
                  value: mongodb-internal  
                - name: DATABASE_PORT
                  value: "27017"
                - name: DATABASE_NAME
                  valueFrom:
                    secretKeyRef:
                      name: mongodb 
                      key: mongo-url
                - name: DATABASE_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: mongodb 
                      key: username
                - name: DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mongodb 
                      key: password
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - digital-strapi
            from:
              kind: ImageStreamTag
              name: 'digital-strapi:dev'
              namespace: xdwiwd-tools
            lastTriggeredImage: >-
              docker-registry.default.svc:5000/xdwiwd-tools/digital-strapi@sha256:cf3813e27bf4b26ee0db4fec39253ba88aa8cee1e6bf3ada20ce7aefa42b1e01
          type: ImageChange
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      generation: 2
      labels:
        app: digital-strapi
      name: digital-strapi
