---

  - name: create build in tools namespace using head/pulls/{{ PR }} as ref 
    shell: >
      oc process -n "{{ tools_namespace }}" -f "../openshift/templates/strapi/bc.yaml" {{ build_params }} | 
      oc apply -n "{{ tools_namespace }}" -f -
    vars:
      GIT_REF: 'pull/{{ PR }}/head'
      build_params: "{{ lookup('template', './templates/build_strapi.param.j2') }}"
  - name: cancel any existing builds
    shell: oc -n "{{ tools_namespace }}" cancel-build bc/{{ strapi_infra_name }}-{{ version }}
  - name: start build
    shell: oc -n "{{ tools_namespace }}" start-build {{ strapi_infra_name }}-{{ version }}
