---
  - name: Fetch imagestream {{ react_infra_name }}:{{ version }}
    set_fact: 
      imagestreamtag: "{{ lookup('k8s', kind='ImageStreamTag', namespace=image_namespace, resource_name=react_infra_name + ':' + version) }}"
    until: (imagestreamtag|length > 0)
    delay: 60
    retries: 20
    ignore_errors: True
  - debug: 
      msg: 
        - Image Tag {{ version }} does not exist in {{ image_namespace }}. 
        - This is because either you have not run ansible-playbook build-react.yaml -e PR={{ PR }}
        - Or the buildconfig has been run but isn't complete
        - OR the build failed
    when: "imagestreamtag|length == 0"
  - name: Setting image exists
    set_fact:
      image_exists: "imagestreamtag|length > 0"
