---
  - hosts: localhost
    gather_facts: no
    vars:
      image_namespace: "{{ tools_namespace }}"
      namespace: "{{ test_namespace }}"
      # in test and prod namespaces they only house one tag: prod | test
      new_image_tag: "{{ test_image_tag }}"
      suffix: "{{ new_image_tag }}"
      version: "{{ new_image_tag }}"
      infra_name: "{{ react_infra_name }}"
    tasks:

      - name: Check if valid author
        include_tasks: ./tasks/check_if_valid_pr_author.yaml

      - name: Check if should build 
        include_tasks: ./tasks/check_if_should_build.yaml
        when: is_valid_author

      - debug:
          msg:
            - not rebuilding react project, the commits match
        when: not should_build

      - name: Build React Project
        include_tasks: ./tasks/build_react.yaml
        when: 
          - should_build
          - is_valid_author

      - name: Wait for build to complete
        include_tasks: ./tasks/wait_for_build_to_complete_react.yaml



