---
  - hosts: localhost
    gather_facts: no
    vars:
      version: "{{ lookup('template', './templates/pr_tag.j2') }}"
      deploy: false
      image_namespace: "{{ tools_namespace }}"
      suffix: "{{ version }}"
      infra_name: "{{ react_infra_name }}"
    tasks:
      - name: Pre checks
        include_tasks: ./tasks/check_pr_exists.yaml

      - name: Check if valid author
        include_tasks: ./tasks/check_if_valid_pr_author.yaml

      - name: Check if should build 
        include_tasks: ./tasks/check_if_should_build.yaml
        when: is_valid_author

      - debug:
          msg:
            - not rebuilding react project, the commits match
        when: not should_build

      - name: Build React Project
        include_tasks: ./tasks/build_react.yaml
        when: 
          - should_build
          - is_valid_author

