---
  - hosts: localhost
    vars:
      version: "{{ lookup('template', './templates/pr_tag.j2') }}"
      namespace: "{{ dev_namespace }}"
      suffix: "{{ version }}"
      image_namespace: "{{ tools_namespace }}"
    tasks:
      - name: check images
        include_tasks: ./tasks/check_image_exists.yaml
      - name: Delete PR Deployment
        include_tasks: ./tasks/delete_deployment.yaml
      - name: Delete PR images in tools name space.
        include_tasks: ./tasks/delete_images.yaml