on:
  workflow_dispatch:
    paths:
    - 'react-frontend/src'
    - 'react-frontend/package.json'
  schedule:
    - cron: 0 0 3 * * # run monthly on the 3rd day
  repository_dispatch: # run manually
    types: [check-link]
  # push:
  # ...

name: Broken Link Check
jobs:
  run:
    runs-on: ubuntu-latest
    env:    
      working-directory: ./react-frontend
    steps:
    - uses: actions/checkout@v1
    - name: build tests
      run: npm install
      working-directory: ${{env.working-directory}}
    - name: Run url tests
      run: npm run url-test
      working-directory: ${{env.working-directory}}
    - name: Create team issue
      if: ${{failure()}}
      uses: imjohnbo/issue-bot@3daae12aa54d38685d7ff8459fc8a2aee8cea98b
      with:
        assignees: "alex-struk"
        labels: "bug"
        title: "Broken urls found on site"
        body: |
          ### The broken link checker action found a broken link!
          Please check the action output in GitHub for details.
        pinned: true
        close-previous: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
