name: Deploy React to Test
on: 
  pull_request:
    branches:
      - develop
    types: [closed]
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.1'
      - name: Store PR Num in env
        uses: actions/github-script@v3
        with:
          github-token: ${{github.token}}
          script: |
            const prNumber = context.payload.number;
            core.exportVariable('PULL_NUMBER', prNumber);
      - name: install oc
        run: |
          curl -O https://mirror.openshift.com/pub/openshift-v3/clients/3.11.232/linux/oc.tar.gz > oc.tar.gz
          tar xvzf oc.tar.gz 
          ls -l
          sudo mv oc /usr/local/bin
          rm oc.tar.gz
          oc version
          pip3 install ansible openshift
      - name: Check user permissions for admin
        id: check
        uses: scherermichael-oss/action-has-permission@master
        with:
          required-permission: admin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Cancel workflow if user does NOT have sufficient permissions
        if: "! steps.check.outputs.has-permission"
        run: exit 1
      - name: login to oc client
        run: ansible-playbook ansible/oc-login.yaml -e OPENSHIFT_SERVER_URL=${{ secrets.OPENSHIFT_SERVER_URL_OC4 }} -e CICD_SA_ACCOUNT_TOKEN=${{ secrets.CICD_SA_ACCOUNT_TOKEN_OC4 }}
      - name: build react app
        run: ansible-playbook ansible/build-react-for-test.yaml -e PR=$PULL_NUMBER -e ENV=test -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -v
      - name: deploy react app
        run: ansible-playbook ansible/deploy-react-to-test-prod.yaml -e PR='' -e ENV=test -v
      - name: create github deployment to test/prod
        run: ansible-playbook ansible/create-gh-deployment.yaml -e PR=$PULL_NUMBER -e ENV=test -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -e OPENSHIFT_SERVER_URL=${{ secrets.OPENSHIFT_SERVER_URL_OC4 }} -v